import React from 'react';
const ChangeValue = function (props) {
    const first = 'Qazaq jerinde ejelgi dáýirden bastap saq, ǵun, úısin, qańly sıaqty memleketter, orta ǵasyrlarda Túrki, Batys Túrki, Túrgesh, Qarluq, Qımaq, Qypshaq t.b., mońǵol shapqynshylyǵynan keıingi kezeńderde Aq Orda, Moǵolstan, Noǵaı Ordasy sıaqty memleketter boldy. Al Qazaq handyǵynyń qurylýy "jańa memlekettik júıeniń" bastalýy boldy. Qazaq halqy qalyptasýǵa bet burǵan kezeńde halyqtyń turaqty ómiri men tirshiligin, atamekenniń tutastyǵyn, damýǵa degen talpynysyn qamtamasyz ete alatyn jalǵyz faktor – memleket tutastyǵynyń bolýy edi. Mundaı qoǵamdyq suranysty der kezinde túsingen Kereı men Jánibek boldy. Qazaq handyǵy sharýashylyqtyń damýy, óndirgish kúshterdiń ósýi, feodaldyq qatynastardyń qalyptasýy nátıjesinde erte zamannan beri ulan-baıtaq Orta Azıany mekendegen kóshpendi taıpalardyń biryńǵaı etnıkalyq top quraǵan qazaq halqynyń birigýi arqyly XV ǵasyrdyń orta sheninde quryldy.'
    const second = 'Qazaq handyǵynyń alǵashqy qurylǵan jeri: Jetisýdyń batysy. Qazaq handyǵynyń alǵashqy qurylǵan kezdegi alyp jatqan jeri Dýlatıdyń jazýynsha: Qozybasy men Shý aýmaǵy. Qazaq handyǵynyń alǵashqy qurylǵan kezdegi terıtorıasy: Shý men Talas ózenderi mańy. Qazaq handyǵynyń alǵashqy terıtorıasy: Shý men Talas ózenderi mańy. Qazaqstannyń jer aýmaǵy : sharyqtaý kezinde 2,5 mln sharshy km.'
    const third = '1770-1800 jyldar aralyǵyndaǵy kóterilister | 1773-1775-Kishi júzben Orta júz qazaqtarynyń E.Pýgachev bastaǵan sharýalar kóterilisine qatysýy. | 1783-1797-Kishi júz qazaqtaryń Syrym Datuly bastaǵan ult-azattyq kóterilisi. | 1800-1900 jyldar aralyǵyndaǵy kóterilister | 1821-Qazaqstannyń ońtústigindegi qazaqtardyń Qoqan handyǵyna qarsy kóterilisi. | 1822-1825-Jolaman Tilenshiuly bastaǵan qazaqtardyń patsha úkimetine qarsy kóterilisi. | 1836-1838-Bókeı handyǵy qazaqtarynyń Isataı Taımanuly men Mahambet Ótemisuly bastaǵan kóterilisi. | 1837-1847-Qazaqtardyń Kenesary Qasymuly bastaǵan ult-azattyq kóterilis.'
    const fourth = 'XVIII ǵasyrdyń basynda Qazaq handyǵy egemendi, táýelsiz jáne táýelsiz memleket boldy jáne halyqaralyq-quqyqtyq óriste basqa memleketter moıyndaǵan tolyqqandy halyqaralyq sýbekt retinde áreket etti. Bul onyń batystaǵy, soltústiktegi, Shyǵystaǵy jáne ońtústiktegi memlekettermen dıplomatıalyq qatynastary týraly aqparat kózderimen rastalady. Osy kezeńde Eýropany, Qytaıdy, Úndistandy, Aýǵanstandy jáne Orta Azıany Uly Jibek joly arqyly baılanystyratyn Qazaqstan aýmaǵy arqyly saýda aǵyndary jandandy; munda qajylar ótip, áskerı jasaqtar ótti. Saýda Astrahan men Mańǵyshlaq arasyndaǵy Kaspıı teńizi arqyly, sondaı — aq Kaspıı teńiziniń soltústik jaǵalaýy, Buhara jáne Hıva arqyly qurlyq arqyly júrgizildi. Qytaıdan Batysqa qaraı eń kóp júretin baǵyttar Jetisý men Ońtústik Qazaqstan arqyly ótetin tranzıttik jol boldy. Qazaq dıplomatıasy ózinen burynǵylardyń — ejelgi túrkiler men altyn ordalyqtardyń baı arsenalynyń formalary men ádisterine súıendi. Qazaq handyǵy bıleýshileriniń Reseı memleketimen dıplomatıalyq baılanystarynyń negizgi maqsaty tatý kórshilik qatynastardy ornatý jáne damytý boldy. Dıplomatıalyq komısıalardyń aldyna negizinen saýdany damytýǵa nemese áskerı odaqtar qurýǵa baǵyttalǵan naqty, praktıkalyq mindetter qoıyldy. Reseı memleketimen syrtqy qatynastar. Qazaq handyǵy men Máskeý (orys) memleketiniń dıplomatıalyq baılanystarynyń bolý faktisi eki memlekettiń — qazaq pen orys arasyndaǵy teń quqyly áriptestik týraly Kýáligimen erekshelenedi. Sol kezdegi orys tarıhı derekterinde qazaq dıplomattaryna qatysty "Elshi" termıni qoldanylady. Qytaımen syrtqy qatynastar. Qazaq handyǵy men Qytaı arasynda saýda-ekonomıkalyq baılanystar ǵana emes, sondaı-aq óte tyǵyz dıplomatıalyq qatynastar boldy. Qazaq-Qytaı qatynastaryn damytýda elshiler, elshiler mańyzdy ról atqardy. Dıplomatıalyq sıpattaǵy elshiler men joldaýlardyń turaqty almasýy, bıleýshiler arasyndaǵy merzimdi kezdesýler elder arasyndaǵy qalypty memleketaralyq qatynastardy kórsetedi. "Jylqynyń ornyna Jibek" qaǵıdaty boıynsha ózara saýda qarqyndy damydy.'
    if(props.example === "QURYLÝY"){
        return <p>{first}</p>
    } else if(props.example === "JERI"){
        return <p>{second}</p>
    } else if(props.example === "KÓTERILISTERI"){
        return <p>{third}</p>
    } else if(props.example === 'ODAQTAR'){
        return <p>{fourth}</p>
    }
  };


export default ChangeValue;